select * from INV_TBTAREAS where id ='52489'

select * from INV_TBTAREAS_CTO where id ='33144'

select * from INV_tbTareas_Bloqueos  where id_Tarea ='33144'
select * from INV_tbBloqueos_Gescales  where id ='33144'

select * from INV_tbTareas_Desbloqueos  where id_Tarea ='52489'
select * from INV_tbDesbloqueos_Gescales where id ='52489'

select * from INV_TBARCHIVOS where idTarea = '52489'



select * from INV_TBTAREAS where id ='52489'

select * from INV_TBTAREAS_CTO where id ='52489'

select * from INV_tbTareas_Bloqueos  where id_Tarea ='52489'
select * from INV_tbBloqueos_Gescales  where id ='52489'

select * from INV_tbTareas_Desbloqueos  where id_Tarea ='52489'
select * from INV_tbDesbloqueos_Gescales where id ='52489'

select * from INV_TBARCHIVOS where idTarea = '46725'




SELECT * FROM INV_CTOS WHERE COD_CTO = '268998'

SELECT INV_CTOS.NUMERO FROM INV_TBTAREAS INNER JOIN INV_TBTAREAS_CTO ON INV_TBTAREAS_CTO.ID = INV_TBTAREAS.id INNER JOIN INV_CTOS ON INV_CTOS.COD_CTO = INV_TBTAREAS_CTO.COD_CTO WHERE INV_TBTAREAS.ID = '52486' 
--INSERT INTO INV_tbTareas_Bloqueos (id_Tarea, Tipo_Afectacion, id_Motivo) VALUES ('52485', '1', '1')

SELECT * FROM INV_VIEW_DATOS_TODO WHERE ID_REGION IS NOT NULL and REGION = 'Levante' and PRIORIDAD = '2' and ESTADO = 'Pendiente' and USUORIGEN like '%usuario prueba%' and id_actividad = '6' and id_Subactividad = '65' 

SELECT INV_tbBloqueos_Gescales.COD_GESCAL AS GESCAL, INV_tbBloqueos_Gescales.ID AS ID_TAREA_GESCAL FROM INV_TBTAREAS INNER JOIN INV_tbBloqueos_Gescales ON INV_tbBloqueos_Gescales.ID = INV_TBTAREAS.id

select * from INV_VIEW_DATOS_TODO where ID_ACTUACION = '87586'
select * from INV_TBTAREAS where ref = '1470207662967'
select * from INV_VIEW_DATOS_TODO where REF_ASOCIADA = '1444824474005'
select * from INV_TBTAREAS where id_Actuacion ='87586'
select * from INV_RD
where ID_ACTUACION = '87586'
select * from inv_ra
where ID = '262'

SELECT TOP 1 RA.ID_GD AS ID_GD_RA, RA.ID_FDTT AS ID_FDTT_RA, RA.EECC_CARGA_RA_DISEÑO AS EECC_CARGA_DIS_RA, RA.Fx_ENVIO_RA_DISEÑO AS FECHA_ENVIO_DIS_RA, RA.Fx_ENTREGA_RA_DISEÑO AS FECHA_ENTREGA_DIS_RA, RA.EECC_CARGA_RA AS EECC_CARGA_RA, V.CABECERA AS CABECERA_RA, RA.FECHA_ENVIO AS FECHA_ENVIO_RA, RA.FECHA_ENTREGA AS FECHA_ENTREGA_RA, V.PROVINCIA AS PROVINCIA_RA, RA.FX_AUDITADO_INF AS FX_AUDITORIA_RA, RA.FX_REV_AUDITADO AS FX_REV_AUDITORIA_RA, RA.AUDITADO_POR AS AUDITADO_POR_RA, RA.OBSERVACIONES_AUDITORIA AS OBS_AUDITORIA_RA, V.ACT_JAZZTEL AS ACT_JAZTELL_RA, V.ACT_ID_FDTT AS ACT_ID_FDTT, RA.ESTADO_RA_FDTT AS ESTADO_RA_FDTT, RA.REPAROS AS REPAROS_RA, RA.N_AUDITORIAS AS N_AUDITORIAS_RA, V.ARBOL AS ARBOL_RA, RA.PL4 AS ESTADO_AB_PL4_RA, RA.SUC AS SUC_RA, RA.CARTAS_EMPALME AS CE_RA, RA.AB_RA_GIS AS AB_RA_GIS, RA.EECC_DISEÑO_RA AS EECC_DISENO_RA, RA.EECC_CONSTRUCCION AS EECC_CONSTRUCCION_RA, RA.FX_INICIO_CONSTRUCCION AS FECHA_INI_OBRA_RA, RA.FX_FIN_CONSTRUCCION AS FECHA_FIN_OBRA_RA, RA.SEGUIMIENTO_RA AS SEGUIMIENTO_RA, RA.RESPONSABLE_CARGA AS RESPONSABLE_CARGA_RA, RA.ESTADO_CARGA_GIS AS ESTADO_GIS_RA, RA.ESTADO_RA_FDTT AS ESTADO_RA, RD.ID_GD AS ID_GD_RD, RD.ID_FDTT AS ID_FDTT_RD, RD.EECC_CARGA_RD_DISENO AS EECC_CARGA_RD_DISENO, RD.DIA_ENVIO_DISENO AS DIA_ENVIO_DISENO_RD, RD.DIA_ENTREGA_DISENO AS DIA_ENTREGA_DISENO_RD, RD.ID_ZONA AS ID_ZONA_RD, V.REGION AS REGION_RD, RD.EECC_CARGA_RD AS EECC_CARGA_RD, RD.FECHA_ENVIO AS FECHA_ENVIO_RD, RD.FECHA_ENTREGA AS FECHA_ENTREGA_RD, RD.ESTADO_AB_PL4 AS ESTADO_AB_PL4_RD, V.ACT_TESA AS ACT_TESA_RD, RD.AUDITADO_FECHA AS AUDITADO_FECHA_RD, RD.AUDITADO_POR AS AUDITADO_POR_RD, RD.REPAROS AS REPAROS_RD, RD.OBSERVACIONES_AUDITORIA AS OBSERVACIONES_AUDITORIA_RD, V.ACT_JAZZTEL AS ACT_JAZZTEL_RD, V.ACT_ID_FDTT AS ACT_ID_FDTT_RD, RD.GESTOR AS GESTOR_RD, RD.EECC_DIS_RD AS EECC_DIS_RD, RD.EECC_CONS_RD AS EECC_CONS_RD, RD.Fx_fin_CONS_RD AS Fx_fin_CONS_RD, RD.FASE AS FASE_RD, RD.UUII_AI AS UUII_AI_RD, RD.FIR AS FIR_RD, RD.INC AS INC_RD, RD.AS_BUILT_ARBOL AS AS_BUILT_ARBOL_RD, RD.AIE2E AS AIE2E_RD, RD.Fx_ENTRADA_PL_CAMPO AS Fx_ENTRADA_PL_CAMPO_RD, RD.Fx_ACTUALIZACION_PL_CAMPO AS Fx_ACTUALIZACION_PL_CAMPO_RD, RD.Observaciones_PLANO_CAMPO AS Observaciones_PLANO_CAMPO_RD, RD.FX_INTERCAMBIO AS FX_INTERCAMBIO_RD, RD.BLOQUEADO AS BLOQUEADO_RD, RD.Fx_BLOQUEADO AS Fx_BLOQUEADO_RD, RD.Fx_SOL_BLOQUEO AS Fx_SOL_BLOQUEO_RD, RD.OBS_BLOQUEO AS OBS_BLOQUEO_RD FROM INV_VIEW_DATOS_TODO AS V LEFT JOIN INV_RD AS RD ON V.ID_ACTUACION = RD.ID_ACTUACION LEFT JOIN INV_RA AS RA ON RD.ID_RA = RA.ID WHERE V.ID_ACTUACION = '87586' 
SELECT INV_tbRoles.rol FROM INV_tbUsuarios INNER JOIN INV_tbRoles on INV_tbUsuarios.idRol=tbRoles.id_Rol WHERE INV_tbUsuarios.usuario='usu'

update INV_tbUsuarios set idRol = '2' where usuario='usu'
select * from INV_tbUsuarios where usuario='usu'
select * from INV_tbRoles
update INV_TBTAREAS set idEst = '1' where id = '52487'
select * from inv_tbestados
SELECT * FROM INV_tbTareas WHERE REF = '52487' 

select * from inv_actuaciones WHERE ACT_JAZZTEL = 'ALB10002-CR000017-01'

-- UPDATE inv_actuaciones SET HUELLA = NULL WHERE ACT_JAZZTEL = 'ALB10002-CR000017-01'
SELECT id_usu FROM INV_tbUsuarios WHERE usuario='usu' 